version: "3.9"
services:
  umbraco:
    image: yael_project
    build:
      context: .
    ports:
     - "8080:8080"
    volumes:
      # Volume for App_Data to persist data
      - umbraco_appdata:/app/App_Data
      # Volume for media files to persist uploaded media
      - umbraco_media:/app/wwwroot/media

volumes:
  # Define named volume for App_Data
  umbraco_appdata:
  # Define named volume for media files
  umbraco_media:
